### ISSUE TITLE
`..` vs `_` to ignore one thing

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang-nursery/fmt-rfcs#49]
```rust
enum Foo {
  Bar(i32),
  Lol(i32)
}

// ...
match x {
  Bar(k) => println!("its bar {}", k),
  Lol(_) => println!("its some lol")
}

// vs
match x {
  Bar(k) => println!("its bar {}", k),
  Lol(..) => println!("its some lol")
}
```

Which should we prefer, since they're equivalent? Started from [here](https://www.reddit.com/r/rust/comments/5jserj/announcing_rust_114/dbipkoa/)

**Comment by nrc** [comment]
I default to using `_` since usually if someone adds a field to `Lol`, I want the compiler to remind me. However, sometimes I really don't care about any fields, and will use `..`. I.e., my usage depends on semantics, which is not very useful for Rustfmt, but maybe OK for a style guide.

**Comment by solson** [comment]
Just like @nrc, I use `_` for defensive programming, but sometimes I'm effectively matching on the enum tag, ignoring all fields, in which case `..` makes sense if if there's currently one field.

**Comment by joshtriplett** [comment]
Likewise, I use both depending on the semantics I want.  I don't think the style guide should express any preference for one over the other.

**Comment by steveklabnik** [comment]
>  the Rust pattern matching documentation should have a good example showing exactly what your comment in that thread did: that _ matches exactly one field, while .. matches all fields regardless of number.

It does show them off in the same section, or at least, the current book does. New book isn't done yet with patterns.

**Comment by nrc** [comment]
So, I feel like we have two options - do nothing and leave it to the docs, or to add a discussion for when to use `..` or `_` in the style guide (I don't think doing any reformatting or making a simple recommendation are on the table at this point).

My opinion is that this falls into 'good coding practice' rather than formatting and while it might have a place in a more general style guide, it doesn't in our more formatting focussed ones. What do others think?

**Comment by joshtriplett** [comment]
@nrc To the extent it belongs in a more general style guide, I think it would consist of advice about when to use which, rather than a preference for which to use.  "In a pattern, use `_` to ignore a specific single value when you want to review and consider the code if the number of values changes.  Use `..` to ignore a single value when you want the code to remain identical even if the number of values changes, such as if the code only depends on the enum variant but never any value within that variant."

**Comment by chriskrycho** [comment]
Because the semantics are different, I think it would be very surprising and not in a good way if running `rustfmt` changed it from one to the other, so I'd agree with everything said above and argue strongly against switching.
