### ISSUE TITLE
Should extern "C" include "C"

### ISSUE THREAD

**Issue by nrc** [rust-lang-nursery/fmt-rfcs#52]
I.e., should we format `extern "C" fn` as that or `extern fn`?

Previous discussion: https://github.com/rust-lang-nursery/rustfmt/issues/451

**Comment by ubsan** [comment]
I use `extern fn` near exclusively, personally.

**Comment by steveklabnik** [comment]
I was told in review once that `extern fn` was preferred, so it's what I use.

**Comment by solson** [comment]
+1 for the abbreviated version. We should either use it or deprecate it, and I've seen no signs of a plan to deprecate.

**Comment by nrc** [comment]
> We should either use it or deprecate it

There's been a very high bar for this, generally, so even if it were disapproved of, it would be unlikely to be deprecated.

**Comment by solson** [comment]
Good point. I guess I actually mean I've seen no signs that it's disapproved of.

**Comment by joshtriplett** [comment]
I'd prefer `extern fn` for the one-line case.  For a block of functions, `extern "C" {` seems fine.

**Comment by petrochenkov** [comment]
I always use `extern "ABI"` because the syntax is silly to start with.
"C" is the important part of this modifier and there's nothing "extern" in function with body and non-Rust ABI. I with it was `abi "C" fn()` and `extern abi "C" { ... }` without default ABI, but the ship has sailed long ago.

**Comment by japaric** [comment]
I have the strong opinion that we should be explicit here. Because:

- It makes the code self documenting. Or at least it better expresses the intention of the programmer.

``` rust
extern "C" {
    fn foo();
}
```

This (most likely) indicates that `foo` comes from a C library.

``` rust
pub extern "C" fn bar() { .. }
```

This (most likely) indicates that `bar` will be used by a C library.

``` rust
extern "Rust" {
    fn main();
}
```

Whereas, this indicates that `main` comes from a Rust crate.

- "C" is not the only ABI that Rust has but seeing `extern fn` everywhere (as "C" is the most common non-Rust ABI) could make people believe that's the only way to use `extern`.

For example, the Rust port of compiler-rt, the compiler-builtins crate, has to use the "aapcs" ABI for the aeabi intrinsics because that's the calling convention that LLVM uses. Every other symbol has to use the "C" ABI.

``` rust
pub extern "aapcs" fn __aeabi_memcpy(..) { .. }
pub extern "C" fn __floatundidf(..) { .. }
```

Getting the ABI wrong, e.g. using just `extern fn` everywhere, can lead to [nasty](https://github.com/rust-lang/rust/issues/37559) ABI mismatch [bugs](https://github.com/rust-lang/rust/issues/37630).

- It would hopefully be didactic for beginners. Upon their first encounter with a `extern "C"` block / `fn`, they may ask themselves "Wait, can `"C"` be a different string?", then they'll check the documentation and learn about the other ABIs, specially about the ones that are not about FFI like `"msp430-interrupt"` and `"ptx-kernel"`.

---

> I wish it was abi "C" fn() and extern abi "C" { ... } without default ABI, but the ship has sailed long ago.

I agree 100%.

**Comment by nrc** [comment]
I would like to move to FCP here with an inclination towards being explicit. I think @japaric makes a great case above and we need to choose one way or the other.

**Comment by solson** [comment]
I am also convinced by @japaric's arguments.

> Getting the ABI wrong, e.g. using just extern fn everywhere, can lead to nasty ABI mismatch bugs.

If this is really so dangerous, we should not just stop using `extern fn` in rustfmt but also lint against it (maybe in clippy?). I would suggest a lint in rustc but it would probably annoy too broad a group of people.

**Comment by nrc** [comment]
Seems we have consensus and no further comments

**Comment by dns2utf8** [comment]
So do I get this right? Rust will go the more expressiv way with `extern "C" fn`?

**Comment by nrc** [comment]
We've changed our process: rather than requiring a full RFC, a PR to close this issue only requires making the changes discussed here to the [style guide](https://github.com/rust-lang-nursery/fmt-rfcs/blob/master/guide/guide.md). You can see more details about the process in the [readme for this repo](https://github.com/rust-lang-nursery/fmt-rfcs#the-formatting-rfc-process).

If you'd like to help with this work, let me know, I'd be very happy to help you help us.
