### ISSUE TITLE
Ranges

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang-nursery/fmt-rfcs#60]
I hope this is the right place to write down this suggestion.

Currently the standard formatting is:

    let x = 2 + 5;
    for i in 0..3 {}
    for i in 0...3 {}
    let a1 = [10, 20, 30, 40];
    let a2 = &a[..2];
    let a3 = &a[1..];
    let a4 = &a[..];

But I'd like the standard formatting to help the programmer better tell apart the floating point literal "0.3" from the interval "0..3". I see the ".." (and "...") as an operator, just like "+", so I'd like that code formatted like this:

    let x = 2 + 5;
    for i in 0 .. 3 {}
    for i in 0 ... 3 {}
    let a1 = [10, 20, 30, 40];
    let a2 = &a[.. 2];
    let a3 = &a[1 ..];
    let a4 = &a[..];

That means to have a space before an after the "..", unless the start or end values are missing.

**Comment by solson** [comment]
What is an example where you could be confused about `0.3` and `0..3`? I understand the theoretical desire not to confuse them, but I have never seen this problem in practice. It's always clear to me from context.

* `for i in _` would never have a float literal, because they aren't `IntoIterator`.
* `array[_]` would never have a float literal, since we don't index things with floats.

**Comment by leonardo-m** [comment]
Formatting also has aesthetic components. I see the dotdot as an operator between 0 and 3. I agree that in most cases there's no actual ambiguity. A case like this is rare:

    #![allow(unused_variables)]
    fn main() {
        let x = 3.5;
        let y = 3..5;
    }

There are people that think that "..." (dotdotdot) should be replaced with a more evident syntax, that better denoted the closeness of the interval and tells it apart better from ".." (dotdot), so the visibility problems are not to be ignored.

**Comment by solson** [comment]
> Formatting also has aesthetic components.

This is true, but it's very subjective. I think that `3..5` looks prettier, and it's currently more common.

> There are people that think that "..." (dotdotdot) should be replaced with a more evident syntax, that better denotes the closeness of the interval and tells it apart better from ".." (dotdot), so the visibility problems are not to be ignored.

The difference between `..` and `...` is far more important because they actually *can* be used in the same places, changing the meaning of the code, unlike `.` and `..`.

**Comment by solson** [comment]
(I am also one of the people who think we should get rid of `...`. I think it's harder even to tell between `..` and `...` compared to `.` and `..`, like how humans are better at telling between 1 apple or 2 apples at a glance than between 11 and 12. It's a less pronounced difference here, but still bad because of our rapid scanning and the small size of the dots.)

**Comment by petrochenkov** [comment]
`..` and `...` are either binary or unary operators, so I apply the same common rules to them - binary operators have spaces, unary operators don't have spaces.
```
a .. b
a ... b
a..
a...
..a
...a
```

**Comment by nrc** [comment]
This is actually one of the more controversial topics, as well as the aesthetic considerations and consistency with the unary case, there is also the issue of sub-expressions, e.g, `a..b + c` (current rustfmt formatting) has precedence `a..(b + c)`, but doesn't look like it because the sub-expression has spaces, but the range expression does not. However, no spaces around the `..` looks better (to me), is used much more widely and makes intuitive sense in the common, non-sub-expression case.

**Comment by nrc** [comment]
I'd like to extend this issue to cover all aspects of formatting ranges

**Comment by nrc** [comment]
> .. and ... are either binary or unary operators, so I apply the same common rules to them - binary operators have spaces, unary operators don't have spaces.

This is an interesting angle, and I think worth considering. The obvious downside is inconsistency between `..x` and `0 .. x`. I'm also not sure that the binary case is actually ideal, I think I prefer `0..x` in most cases.

**Comment by nrc** [comment]
My current thinking is that not having spaces in ranges is more common and there is not really overwhelming support evidence to change that. IMO, it is the right choice, but this seems to come down to a subjective aesthetic choice, and possibly how often you use ranges with atomic vs compound expressions.

I propose that we keep no spaces.

I'm not sure there is much more to debate in terms of formatting ranges. Should we allow a line break anywhere in a range expression? I propose we allow (but recommend against) a break after the `..` or `...`, but not before (although this should follow other binary operators, so if we change there, we should here too).

**Comment by joshtriplett** [comment]
I think we should continue writing `1..10` or `x..y` without a space; however, if a range ever happens to have a compound expression or a floating-point number in it, I'd suggest putting spaces around the range operator in those cases.

**Comment by nrc** [comment]
Entering FCP based on this comment - https://github.com/rust-lang-nursery/fmt-rfcs/issues/60#issuecomment-284847897

**Comment by Storyyeller** [comment]
IMO, complex expressions as range bounds should always be parenthesized. Even if you just put spaces around the dots, it would still be confusing. It's hard to tell at a glace what `0 .. x + 1` means.
