### ISSUE TITLE
Attribute / doc comment ordering

### ISSUE THREAD

**Issue by solson** [rust-lang-nursery/fmt-rfcs#72]
@stebalien pointed out this code in the latest version of this [rustfmt example](https://github.com/rust-lang-nursery/fmt-rfcs/blob/0dbf002dd2b7d036e2f3e59e7116ff6f17fd4368/example/lists-elided.rs#L20-L24):

```rust
#[derive(Eq, PartialEq, Debug, Copy, Clone)]
/// Formatting tactic for lists. This will be cast down to a
/// DefinitiveListTactic depending on the number and length of the items and
/// their comments.
pub enum ListTactic {
```

And they made a good point:

> For items with long doc comments, it will be really hard to figure out what struct/function the attributes apply to.

Placing the doc comment in the middle splits the definition into two pieces. I'm strongly in favor of specifying this instead:

```rust
/// Formatting tactic for lists. This will be cast down to a
/// DefinitiveListTactic depending on the number and length of the items and
/// their comments.
#[derive(Eq, PartialEq, Debug, Copy, Clone)]
pub enum ListTactic {
```

**Comment by nrc** [comment]
I think Rustfmt just leaves the ordering as it started out. I agree that if we were to express a preference, then comments first is better. I'm not sure whether we should express a preference here?

**Comment by joshtriplett** [comment]
I do prefer comments-first, but I would also find it surprising for rustfmt to do that level of reordering.  (Just as I also think rustfmt shouldn't reorder code/declarations at the module level.)

**Comment by solson** [comment]
I definitely think rustfmt *should* do this reordering, because I never want to run into this situation:

```rust
/// ... this long doc comment scrolls off the top of my screen ...
/// The last few lines
/// of the doc comment.
struct Foo {
    ...
}
```

Now I'm thinking `Foo` has no attributes... but little do I know, there are a bunch of important ones all the way at the top of the doc comment. I have actually run into this problem in real code before, but I forgot to bring it up as a style issue at the time.

**Comment by phaylon** [comment]
I wonder if something like the following ever happened in the wild?

    #[derive( Copy, Clone )]
    /// long documentation
    #[derive( Debug )]
    struct Something;

It could lead to momentary confusion. On the other hand, there might be good use-cases for alternating documentation and attributes that I'm missing, like having comments related to attributes close to them.

**Comment by SergioBenitez** [comment]
I agree that comments should come first, followed by attributes. Further, I believe that `rustfmt` should enforce this ordering. Further, `rustfmt` should coalesce when possible. In particular, two `derive`s should be merged into one if doing so would not exceed the maximum column length.

**Comment by solson** [comment]
I agree with @SergioBenitez's coalescing idea. I see this as very similar to `use`, where my preference is to coalesce and sort:

```rust
use a::c;
use a::b;
```

Into this:

```rust
use a::{b, c};
```

So I would also coalesce and sort this:

```rust
#[derive(B)]
#[derive(A)]
```

Into this:

```rust
#[derive(A, B)]
```

I do this in my own code for consistency, but it's harder to sort lists than lines in my editor, so it would be nice to automate this.

**Comment by olivren** [comment]
The coalesced form is equivalent to the split form for `derive`, but we probably can't generalize it for any attribute, though.

**Comment by emk** [comment]
I definitely agree that comments should come first, then attributes, then the definition. I don't have a strong opinion on whether or not `rustfmt` should enforce it.

**Comment by nrc** [comment]
> I definitely think rustfmt should do this reordering, because I never want to run into this situation:

I don't agree with this reasoning - there are a lot of bad coding practices that I hope never to run into, and some of them could be fixed by a smart enough tool, however, I think mostly they would be out of bounds for rustfmt, which strictly deals with formatting of code.

So the question for me is, does re-ordering count as a 'trivial, semantics-preserving' transformation which most people would regard as 'just formatting'?

Now technically, this is not semantics-preserving - a procedural macro could have attribute form and sees only attributes declared after it, so changing the ordering of doc comments and such a macro *could* change the behaviour of the program. However, this seems surprising and should not happen in practice. At the least such a reordering must be behind a option, but we could make it 'on' by default.

My thoughts are that we should not re-order by default - I expect that situations where people write code in the 'wrong' order to be very rare and where they do, there is a good chance it is deliberate. Furthermore, my experience with Rustfmt so far is that there is a significant minority of users who are very uncomfortable with this kind of change (any change beyond whitespace really) and thus I want to have strong motivation for doing this kind of thing.

**Comment by nrc** [comment]
Entering FCP. Summary:

We will recommend that doc comments should come before attributes on items. Rustfmt will have an option to do this reordering, but it will be off by default.

Rustfmt will have an option to merge `derives` and it will be on by default. (I think Rustfmt should not reorder derives. I don't think this is semantics preserving, and derives are often grouped semantically, e.g., `Eq` with `PartialEq`).

**Comment by WiSaGaN** [comment]
I'm on the fence of merging `derives`. It is much easier to spot whether some structs have derived `serde` if we put `serde` related derives in a separate line:

```rust
#[derive(Deserialize, Serialize)]
#[derive(Clone, Copy, Debug, PartialEq)]
struct Foo {
...
}
```

It seems to me that being coservative in such a case, i.e. support but not default, is a good compromise. I don't have a strong opinion though.

**Comment by CAD97** [comment]
Something that needs to be mentioned is `#[doc = ""]` attributes. As they can be used combined with `#[cfg_attr]` in order to do config-dependent documentation (though that could be a bit of an anti-pattern), reordering attributes can have a semantic effect.

To Rust, a doc comment and an attribute are the same thing, `/// text` is just shorthand for `#[doc = " text"]`. As such, I agree that reordering should not happen by default.
