### ISSUE TITLE
Fix argument/`where` bound asymmetry.

### ISSUE THREAD

**Issue by ticki** [rust-lang-nursery/fmt-rfcs#76]
Argument lists can have multiple args on each line, which isn't true for `where` bounds in the proposed style. In particular, it isn't legal to do

```rust
    pub fn upsert<F, G>(&self, key: K, insert: F, update: G) // Multiple args here. (legal)
    where F: FnOnce() -> V, G: FnOnce(&mut V) { // Multiple bounds here. (NOT legal)
        // blah
```

related to #74

**Comment by nrc** [comment]
We discussed this in #38, to summarise, we think that single line where clauses only make sense if the bounds are very simple, otherwise they are hard to read (more so than arguments). However, if the clauses are this simple, then they are better as inline bounds on the generic arguments (which can be put on a single line). Therefore, there is no situation where single line where clauses with multiple clauses make sense.

(I'm closing because I think we discussed this in depth and we are happy with the asymmetry here. I don't think there is any new information here (c.f., #74, where it is perhaps worth re-considering single line where clauses with a single clause).
