### ISSUE TITLE
From owned (array, Vec, String) to slice (&[T], &str) without deref coercions

### ISSUE THREAD

**Issue by LukasKalbertodt** [rust-lang-nursery/fmt-rfcs#79]
(*I apologize if this issue doesn't fit the scope of `fmt-rfcs`*)

It's a pretty specialized case, but I encountered it many times already and I am always annoyed to see yet another different version. I am talking about expressions in which you want to obtain a slice from the owned version without being able to use deref coercions. This regularly happens in the `match` head expression, in `println!()` arguments and so on. I've seen the following versions:

1. `&v[..]` (full range index)
2. `&*v` (explicit deref)
3. `v.as_ref()` (method from `AsRef` trait)
4. `v.as_slice()` and `s.as_str()` (specialized methods for `Vec` and `String`)

I think one of those versions should be officially endorsed.

**Comment by joshtriplett** [comment]
I don't think it's something that rustfmt should enforce, but the style guide could give a recommendation.

For my part, I'd prefer 4 or 3, though I could live with 1.  I'm not at all a fan of 2.

**Comment by LukasKalbertodt** [comment]
Personally, I don't really like any of those. I think (1) and (2) are especially confusing ("index operation? does this have overhead?" and "`&*` cancel each other out?"). I like (3) most, I think, as it's a general and trait-based solution.

**Comment by ubsan** [comment]
My favorite is `&*`, because I like it. Not really a full reason, except maybe consistency with all deref-able types, it's just my favorite. Close second is `&v[..]`.

**Comment by joshtriplett** [comment]
@ubsan While I know what `&*` does, I find it very line-noise-y.  It's the kind of thing that doesn't express an obvious meaning at a glance, and I think it also makes reading code more challenging for new users.  Before I understood Deref, I found it quite inscrutable, and even once I did, I find it awkward in a complex expression; I find `.as_ref()` or `.as_str()` a better signpost in the middle of an expression.

**Comment by JustAPerson** [comment]
>While I know what &* does, I find it very line-noise-y. It's the kind of thing that doesn't express an obvious meaning at a glance, and I think it also makes reading code more challenging for new users. 

I would argue the opposite. I don't really care that a function requires `&str` when I have a `String`.  When reading code I just want to understand what values are used where. The less space used on trivial type transformations, the better. Because `&*` is the most concise option, I find it preferable for not distracting from the actual meaning of the code.

**Comment by nrc** [comment]
I don't think this counts as a formatting issue and while it is certainly a style issue, our style guide is meant to be limited in scope to formatting rather than all aspects of style (so closing for now).

As you can see, this kind of question gets lots of different opinions. My personal opinion is to use `&*` (option 2). My reasoning is that were you in a context where you can rely on deref coercions you would do so, and this is just making that a tiny bit more explicit, whereas the other options are more different operations (however, I can imagine situations where each of the other options is the 'right' thing to use).
