### ISSUE TITLE
Hexadecimal literal casing

### ISSUE THREAD

**Issue by euclio** [rust-lang-nursery/fmt-rfcs#85]
Should hexadecimal literals be uppercased or lowercased?

```rust
let literal = 0xabcd;
```

vs.

```rust
let literal = 0xABCD;
```

**Comment by ubsan** [comment]
I vote `0xABCD`.

**Comment by joshtriplett** [comment]
*If* we specify this, I'd agree that we should uppercase them.

However, my preferred alternative would be to leave all-uppercase and all-lowercase literals exactly as the user wrote them, and only rewrite those that have mixed uppercase and lowercase (to all-uppercase).

**Comment by repax** [comment]
My impression is that uppercase is more commonly used, but personally I tend to write hexadecimal numbers with lowercase because I find it easy to mistake the following uppercase letters for digits:

`B8`, `D0`

Therefore I suggest that we don't specify case.

**Comment by nrc** [comment]
I'm proposing FCP with: hexadecimal literals must be either upper case or lower case. We recommend that if a literal is mixed case, then it should be reformatted to upper case (and to be clear, this does not mean we *always* recommend using upper case).

**Comment by solson** [comment]
I'd rather read a codebase that used all uppercase or all lowercase hex literals than one with a mix, so I'd prefer specifying that we always uppercase by default. This seems like a prime example of a low cost configuration option to implement, so it should be easy to switch for people who care strongly about lowercase hex literals.

**Comment by joshtriplett** [comment]
@solson I think we should absolutely have a configuration option to force all literals to uppercase or lowercase. However, I really don't think it should be on by default.

As a common source of not wanting to change this: sometimes you're working from documentation (e.g. of hardware or an interface) that uses one particular casing, and you want to match that.

**Comment by repax** [comment]
Yeah. Consistency within the code base would mean that the one-off literal cannot trick you.

If it's not too much to ask, a per-project configuration option would be fabulous for us in the minority. ;)

**Comment by joshtriplett** [comment]
At the risk of bikeshedding: I'm becoming increasingly convinced by the argument that `0x1a2b3c4d` is easier to read (precisely because it looks less uniform) than `0x1A2B3C4D`. It's also easier to type. And, looking over my own code, I tend to use lowercase most of the time.

I do still believe we should leave user literals alone, *unless* they're mixed-case, but for the specific case of mixed-case, I do wonder about something, which I'm not certain is appropriate for rustfmt but which might make it a little more automatic: could rustfmt "remember" the last hex-casing it saw for a consistently-cased literal, and use that casing if it needs to "fix" a mixed-case literal? For instance:

```rust
let c1 = 0x123abc;
let c2 = 0x456dEf; // rustfmt would fix this to 0x456def

// elsewhere
let c47 = 0x123ABC;
let c48 = 0x456dEf; // rustfmt would fix this to 0x456DEF
```

Does that seem plausible? In practice, I'd expect most users to use one casing consistently within their code, so this would have the effect of detecting what casing they tend to use.

(Corner case: rustfmt would still have to have a default for the case where the first literal uses mixed-case, unless it can scan ahead to the next consistent-case literal.)

**Comment by solson** [comment]
> could rustfmt "remember" the last hex-casing it saw for a consistently-cased literal, and use that casing if it needs to "fix" a mixed-case literal

That seems like more work than it's worth.

> As a common source of not wanting to change this: sometimes you're working from documentation (e.g. of hardware or an interface) that uses one particular casing, and you want to match that.

I'd rather see the whole project using that casing if so. I probably wouldn't even notice if a hardware doc said `0xff` and the code said `0xFF`, though.

> I'm becoming increasingly convinced by the argument that `0x1a2b3c4d` is easier to read (precisely because it looks less uniform) than `0x1A2B3C4D`.

I find the latter easier to read, especially in cases like `0xa` vs. `0xA` which I happened to run into a lot. I like that the actual digits part of the literal stands out from the `x` when the character heights are different.

My ordered preference for the default is:
1. All uppercase
2. All lowercase
3. Only fix mixed case

**Comment by joshtriplett** [comment]
> I find the latter easier to read, especially in cases like `0xa` vs. `0xA` which I happened to run into a lot. I like that the actual digits part of the literal stands out from the `x` when the character heights are different.

That's fair, and that is the one thing that bugs me about lowercase hex literals.

**Comment by nrc** [comment]
> could rustfmt "remember" the last hex-casing it saw for a consistently-cased literal

This would not be composable behaviour - you could get a different result running rustfmt on a whole project vs a selection. It would also introduce order dependency, which I'd rather avoid (or introduce a multi-pass architecture).

**Comment by joshtriplett** [comment]
@nrc Fair enough.
